In [1]:
?matrix
matrix

function (data = NA, nrow = 1, ncol = 1, byrow = FALSE, dimnames = NULL) 
{
    if (is.object(data) || !is.atomic(data)) 
        data <- as.vector(data)
    .Internal(matrix(data, nrow, ncol, byrow, dimnames, missing(nrow), 
        missing(ncol)))
}
<bytecode: 0x0000000014353758>
<environment: namespace:base>

matrix                  package:base                   R Documentation

_M_a_t_r_i_c_e_s

_D_e_s_c_r_i_p_t_i_o_n:

     'matrix' creates a matrix from the given set of values.

     'as.matrix' attempts to turn its argument into a matrix.

     'is.matrix' tests if its argument is a (strict) matrix.

_U_s_a_g_e:

     matrix(data = NA, nrow = 1, ncol = 1, byrow = FALSE,
            dimnames = NULL)
     
     as.matrix(x, ...)
     ## S3 method for class 'data.frame'
     as.matrix(x, rownames.force = NA, ...)
     
     is.matrix(x)
     
_A_r_g_u_m_e_n_t_s:

    data: an optional data vector (including a list or 'expression'
          vector).  Non-atomic classed R objects are coerced by
          'as.vector' and all attributes discarded.

    nrow: the desired number of rows.

    ncol: the desired number of columns.

   byrow: logical. If 'FALSE' (the default) the matrix is filled by
          columns, otherwise the matrix is filled by rows.

dimnames: A 'dimnames' attribute for the matrix: 'NULL' or a 'list' of
          length 2 giving the row and column names respectively.  An
          empty list is treated as 'NULL', and a list of length one as
          row names.  The list can be named, and the list names will be
          used as names for the dimensions.

       x: an R object.

     ...: additional arguments to be passed to or from methods.

rownames.force: logical indicating if the resulting matrix should have
          character (rather than 'NULL') 'rownames'.  The default,
          'NA', uses 'NULL' rownames if the data frame has 'automatic'
          row.names or for a zero-row data frame.

_D_e_t_a_i_l_s:

     If one of 'nrow' or 'ncol' is not given, an attempt is made to
     infer it from the length of 'data' and the other parameter.  If
     neither is given, a one-column matrix is returned.

     If there are too few elements in 'data' to fill the matrix, then
     the elements in 'data' are recycled.  If 'data' has length zero,
     'NA' of an appropriate type is used for atomic vectors ('0' for
     raw vectors) and 'NULL' for lists.

     'is.matrix' returns 'TRUE' if 'x' is a vector and has a '"dim"'
     attribute of length 2 and 'FALSE' otherwise.  Note that a
     'data.frame' is *not* a matrix by this test.  The function is
     generic: you can write methods to handle specific classes of
     objects, see InternalMethods.

     'as.matrix' is a generic function.  The method for data frames
     will return a character matrix if there is only atomic columns and
     any non-(numeric/logical/complex) column, applying 'as.vector' to
     factors and 'format' to other non-character columns.  Otherwise,
     the usual coercion hierarchy (logical < integer < double <
     complex) will be used, e.g., all-logical data frames will be
     coerced to a logical matrix, mixed logical-integer will give a
     integer matrix, etc.

     The default method for 'as.matrix' calls 'as.vector(x)', and hence
     e.g. coerces factors to character vectors.

     When coercing a vector, it produces a one-column matrix, and
     promotes the names (if any) of the vector to the rownames of the
     matrix.

     'is.matrix' is a primitive function.

     The 'print' method for a matrix gives a rectangular layout with
     dimnames or indices.  For a list matrix, the entries of length not
     one are printed in the form 'integer,7' indicating the type and
     length.

_N_o_t_e:

     If you just want to convert a vector to a matrix, something like

       dim(x) <- c(nx, ny)
       dimnames(x) <- list(row_names, col_names)
     
     will avoid duplicating 'x'.

_R_e_f_e_r_e_n_c_e_s:

     Becker, R. A., Chambers, J. M. and Wilks, A. R. (1988) _The New S
     Language_.  Wadsworth & Brooks/Cole.

_S_e_e _A_l_s_o:

     'data.matrix', which attempts to convert to a numeric matrix.

     A matrix is the special case of a two-dimensional 'array'.  Since
   

In [2]:
matrix()
matrix(nrow=2, ncol=3)
matrix(0, 2, 3)
matrix(1:6, 2, 3)
matrix(1:6, 2, 3, byrow=TRUE)

[,1]
[1,] NA

[,1] [,2] [,3]
[1,] NA   NA   NA  
[2,] NA   NA   NA

[,1] [,2] [,3]
[1,] 0    0    0   
[2,] 0    0    0

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

In [3]:
#row names and column names
rnames <- c('R1', 'R2')
cnames <- c('C1', 'C2', 'C3')
matrix(1:6, nrow=2, dimnames=list(rnames, cnames))

C1 C2 C3
R1 1  3  5 
R2 2  4  6

In [4]:
#assign row names and column names
x=matrix(1:6, nrow=2)
rownames(x)=c('r1', 'r2')
colnames(x)=c('c1', 'c2', 'c3')
x

c1 c2 c3
r1 1  3  5 
r2 2  4  6

In [5]:
#use dim() to create matrix from vector
x <- 1:6   ##vector
x
dim(x) <- c(3, 2)  ##convert vector to matrix in place
is.matrix(x)   
x 

[1] 1 2 3 4 5 6

[1] TRUE

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

In [6]:
#Matrix Transpose
?t
t(x)

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

t                     package:base                     R Documentation

_M_a_t_r_i_x _T_r_a_n_s_p_o_s_e

_D_e_s_c_r_i_p_t_i_o_n:

     Given a matrix or 'data.frame' 'x', 't' returns the transpose of
     'x'.

_U_s_a_g_e:

     t(x)
     
_A_r_g_u_m_e_n_t_s:

       x: a matrix or data frame, typically.

_D_e_t_a_i_l_s:

     This is a generic function for which methods can be written.  The
     description here applies to the default and '"data.frame"'
     methods.

     A data frame is first coerced to a matrix: see 'as.matrix'.  When
     'x' is a vector, it is treated as a column, i.e., the result is a
     1-row matrix.

_V_a_l_u_e:

     A matrix, with 'dim' and 'dimnames' constructed appropriately from
     those of 'x', and other attributes except names copied across.

_N_o_t_e:

     The _conjugate_ transpose of a complex matrix A, denoted A^H or
     A^*, is computed as 'Conj(t(A))'.

_R_e_f_e_r_e_n_c_e_s:

     Becker, R. A., Chambers, J. M. and Wilks, A. R. (1988) _The New S
     Language_.  Wadsworth & Brooks/Cole.

_S_e_e _A_l_s_o:

     'aperm' for permuting the dimensions of arrays.

_E_x_a_m_p_l_e_s:

     a <- matrix(1:30, 5, 6)
     ta <- t(a) ##-- i.e.,  a[i, j] == ta[j, i] for all i,j :
     for(j in seq(ncol(a)))
       if(! all(a[, j] == ta[j, ])) stop("wrong transpose")

In [7]:
#matrix attributes
rnames <- c('R1', 'R2')
cnames <- c('C1', 'C2', 'C3')
x=matrix(1:6, nrow=2, dimnames=list(rnames, cnames))
x
class(x)  ##data structure type
typeof(x)  ##element data type
dim(x)  ##dimension
length(x)  ##total number of elements
rownames(x)  ##get row names
colnames(x)  ##get column names

C1 C2 C3
R1 1  3  5 
R2 2  4  6

[1] "matrix" "array"

[1] "integer"

[1] 2 3

[1] 6

[1] "R1" "R2"

[1] "C1" "C2" "C3"

In [8]:
#bind vectors into matrix
rbind(c(71,172),c(73,169),c(69,160),c(65,130))
cbind(c(71,73,69,65),c(172,169,160,130))

[,1] [,2]
[1,] 71   172 
[2,] 73   169 
[3,] 69   160 
[4,] 65   130

[,1] [,2]
[1,] 71   172 
[2,] 73   169 
[3,] 69   160 
[4,] 65   130

In [9]:
#access elements in matrix
x
x[,2]
x[2,]
x[2,2]

C1 C2 C3
R1 1  3  5 
R2 2  4  6

R1 R2 
 3  4

C1 C2 C3 
 2  4  6

[1] 4

In [10]:
typeof(x[2,])
class(x[2,])
x[2,][1]

[1] "integer"

[1] "integer"

C1 
 2

In [11]:
x[,c(1,2)]
x[c(1,2),]

C1 C2
R1 1  3 
R2 2  4

C1 C2 C3
R1 1  3  5 
R2 2  4  6

In [12]:
x[,c(2:3)]
x[1,c(2:3)]

C2 C3
R1 3  5 
R2 4  6

C2 C3 
 3  5

In [13]:
x[,-c(2:3)] #exclude

R1 R2 
 1  2

In [14]:
# how does R deal with incomplete data. Cyclically reuse the vector.
x=rbind(c(71,172),c(73),c(69,160),c(65,130)); x
y=cbind(c(71,73,65),c(172,169,160,130)); y
y=cbind(c(71,73,69,65),c(172,169,130)); y

[,1] [,2]
[1,] 71   172 
[2,] 73    73 
[3,] 69   160 
[4,] 65   130

Warning message in cbind(c(71, 73, 65), c(172, 169, 160, 130)):
"number of rows of result is not a multiple of vector length (arg 1)"


[,1] [,2]
[1,] 71   172 
[2,] 73   169 
[3,] 65   160 
[4,] 71   130

Warning message in cbind(c(71, 73, 69, 65), c(172, 169, 130)):
"number of rows of result is not a multiple of vector length (arg 2)"


[,1] [,2]
[1,] 71   172 
[2,] 73   169 
[3,] 69   130 
[4,] 65   172

In [15]:
# how does R deal with incomplete data. Cyclically reuse the vector.
z=matrix(1:6,2,5); z
z=matrix(1:6,2,5, byrow=T); z

Warning message in matrix(1:6, 2, 5):
"data length [6] is not a sub-multiple or multiple of the number of columns [5]"


[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    1    3   
[2,] 2    4    6    2    4

Warning message in matrix(1:6, 2, 5, byrow = T):
"data length [6] is not a sub-multiple or multiple of the number of columns [5]"


[,1] [,2] [,3] [,4] [,5]
[1,] 1    2    3    4    5   
[2,] 6    1    2    3    4

In [16]:
x=c(1,2,3,4,5,6);x
x[1] #index starts from 1
x[2]
x[0] # it is always integer(0) or numeric(0)
print(x[0])
x[2:3] #slicing
x[-2] #drop
x[c(3,5,6)]
x[c(3,5,6,8)] #when index is out of range

[1] 1 2 3 4 5 6

[1] 1

[1] 2

numeric(0)

numeric(0)


[1] 2 3

[1] 1 3 4 5 6

[1] 3 5 6

[1]  3  5  6 NA

In [17]:
#filtering
x[x>3]
x[x<2 | x>3]
which(x>3)  #return indices
which(x<2 | x>3)
which.max(x)
y=c(2,3,3,2)
which.max(y)
?which.max

[1] 4 5 6

[1] 1 4 5 6

[1] 4 5 6

[1] 1 4 5 6

[1] 6

[1] 2

which.min                 package:base                 R Documentation

_W_h_e_r_e _i_s _t_h_e _M_i_n() _o_r _M_a_x() _o_r _f_i_r_s_t _T_R_U_E _o_r _F_A_L_S_E ?

_D_e_s_c_r_i_p_t_i_o_n:

     Determines the location, i.e., index of the (first) minimum or
     maximum of a numeric (or logical) vector.

_U_s_a_g_e:

     which.min(x)
     which.max(x)
     
_A_r_g_u_m_e_n_t_s:

       x: numeric (logical, integer or double) vector or an R object
          for which the internal coercion to 'double' works whose 'min'
          or 'max' is searched for.

_V_a_l_u_e:

     Missing and 'NaN' values are discarded.

     an 'integer' or on 64-bit platforms, if 'length(x) =: n'>= 2^31 an
     integer valued 'double' of length 1 or 0 (iff 'x' has no
     non-'NA's), giving the index of the _first_ minimum or maximum
     respectively of 'x'.

     If this extremum is unique (or empty), the results are the same as
     (but more efficient than) 'which(x == min(x, na.rm = TRUE))' or
     'which(x == max(x, na.rm = TRUE))' respectively.

_L_o_g_i_c_a_l '_x' - _F_i_r_s_t '_T_R_U_E' _o_r '_F_A_L_S_E':

     For a 'logical' vector 'x' with both 'FALSE' and 'TRUE' values,
     'which.min(x)' and 'which.max(x)' return the index of the first
     'FALSE' or 'TRUE', respectively, as 'FALSE < TRUE'.  However,
     'match(FALSE, x)' or 'match(TRUE, x)' are typically _preferred_,
     as they do indicate mismatches.

_A_u_t_h_o_r(_s):

     Martin Maechler

_S_e_e _A_l_s_o:

     'which', 'max.col', 'max', etc.

     Use 'arrayInd()', if you need array/matrix indices instead of 1D
     vector ones.

     'which.is.max' in package 'nnet' differs in breaking ties at
     random (and having a 'fuzz' in the definition of ties).

_E_x_a_m_p_l_e_s:

     x <- c(1:4, 0:5, 11)
     which.min(x)
     which.max(x)
     
     ## it *does* work with NA's present, by discarding them:
     presidents[1:30]
     range(presidents, na.rm = TRUE)
     which.min(presidents) # 28
     which.max(presidents) #  2
     
     ## Find the first occurrence, i.e. the first TRUE, if there is at least one:
     x <- rpois(10000, lambda = 10); x[sample.int(50, 20)] <- NA
     ## where is the first value >= 20 ?
     which.max(x >= 20)
     
     ## Also works for lists (which can be coerced to numeric vectors):
     which.min(list(A = 7, pi = pi)) ##  ->  c(pi = 2L)

In [18]:
# logical vectors
x
x>3
x<2 | x>3  
x<2 & x>3  
all(x>3)
any(x>3)
x %in% c(2,4)

[1] 1 2 3 4 5 6

[1] FALSE FALSE FALSE  TRUE  TRUE  TRUE

[1]  TRUE FALSE FALSE  TRUE  TRUE  TRUE

[1] FALSE FALSE FALSE FALSE FALSE FALSE

[1] FALSE

[1] TRUE

[1] FALSE  TRUE FALSE  TRUE FALSE FALSE

In [19]:
# && and ||
# The longer form evaluates left to right examining only the first element of each vector
x=1:6
x>2
x<5
(x > 2) && (x < 5)
(x[1] > 2) & (x[1] < 5)

[1] FALSE FALSE  TRUE  TRUE  TRUE  TRUE

[1]  TRUE  TRUE  TRUE  TRUE FALSE FALSE

[1] FALSE

[1] FALSE

In [20]:
x = 1; y = 2
(x == 1) & (y == 2)
(x == 1) && (y == 2)

[1] TRUE

[1] TRUE

In [21]:
z = 1:6
(z > 2) & (z < 5)
z[(z>2) & (z<5)]

[1] FALSE FALSE  TRUE  TRUE FALSE FALSE

[1] 3 4

In [22]:
z=1:6
z>2
z<5

[1] FALSE FALSE  TRUE  TRUE  TRUE  TRUE

[1]  TRUE  TRUE  TRUE  TRUE FALSE FALSE

In [23]:
(z > 2) & (z < 5)

[1] FALSE FALSE  TRUE  TRUE FALSE FALSE

In [24]:
(z > 2)  (z < 5)

ERROR: Error in eval(expr, envir, enclos): attempt to apply non-function


In [ ]:
(z > 2)[1] || (z < 5)[1]

In [ ]:
z<2

In [ ]:
z<3

In [ ]:
z<2 || z<3

In [ ]:
(z<2)[1] & (z<3)[1]

In [ ]:
(z > 2) && (z < 5)
z[(z > 2) && (z < 5)]

In [ ]:
(z > 2) && (z < 5)
z[(z > 0) && (z < 5)]  # R recylces the TRUE variable

In [ ]:
z
z[TRUE]
# z[FALSE] ##output nothing

In [ ]:
# more examples of && and ||
a=c(0,1,1)
b=c(0,0,1)
a & b

a | b
a && b # The longer form evaluates left to right examining only the first element of each vector
a || b
a=c(0,1,1)
b=c(1,0,1)
a & b
a | b
a && b
a || b
a=c(1,1,1)
b=c(1,0,1)
a & b
a | b
a && b
a || b

In [ ]:
x # a scalar is like a vector with lengh =1
x>3
x[x>3]

In [ ]:
x[c(FALSE, FALSE, FALSE, TRUE, TRUE, TRUE)]
x<2 | x>3
x[x<2 | x>3]
x[c(TRUE, FALSE, FALSE, TRUE, TRUE, TRUE)]

In [ ]:
x=c(1,2,3,NA,4)
x
is.na(x)
mean(x)
mean(x, na.rm=TRUE)
all(!is.na(x))
any(is.na(x))
x[is.na(x)]=0
x
mean(x)
(1/0)*8 # NA is different from inf

In [ ]:
library() #list all installed packages
library(MASS)
head(survey)
tail(survey)
# data(survey, package="MASS")

In [ ]:
islands

In [ ]:
# islands
class(islands)
head(islands)
islands[1]
islands['Africa']

In [ ]:
library(help=MASS)
library(MASS)
find.package() # list all loaded packages
detach("package:MASS", unload=TRUE)
find.package()

In [ ]:
whales=scan() #doesn't work in jupyter

In [ ]:
data()

In [ ]:
head(rock)

In [ ]:
numbers=scan(file="numbers.txt");numbers

In [ ]:
mytable=read.table(file="table.txt", header=TRUE);mytable
# read.table(file=file.choose()) 
class(mytable)

In [ ]:
LETTERS
data.frame(index=1:26, symbol=LETTERS)

In [ ]:
?data.frame

In [ ]:
mydata=data.frame(col1=1:3, col2=4:6, col3=c('x', 'y', 'z'));mydata

In [ ]:
# col1=9
# rm(col1)
# ls()
names(mydata)
attach(mydata)
col1
col2
# detach(mydata)
# # col1
# # col1
# # col2
mydata$col1
with(mydata, col1)
with(mydata, mean(col1))

In [ ]:
library(ISwR)
data(thuesen)
head(thuesen)
names(thuesen)
attach(thuesen) #add namespace
blood.glucose
detach(thuesen) #remove namespace
thuesen$blood.glucose

In [ ]:
with(thuesen, blood.glucose) # with context
with(thuesen, mean(blood.glucose))
with(thuesen, range(blood.glucose))

In [ ]:
head(energy)
class(energy)
energy[energy$stature== "lean",]

In [ ]:
energy$stature== "lean"

In [ ]:
energy$expend

sort(energy$expend, decreasing = TRUE)
order(energy$expend, decreasing = TRUE)

In [ ]:
energy$stature
order(energy$stature)
order(energy$stature, energy$expend)

In [ ]:
energy$stature

In [ ]:
energy[order(energy$expend),]
energy[order(energy$stature, energy$expend),]
energy[with(energy, order(stature, expend)),] # with context

In [ ]:
subset(energy, stature=="lean" & expend>8)
energy[energy$stature== "lean" & energy$expend>8, ]

In [ ]:
x=split(energy$expend, energy$stature) # split the data in energy$expend into the groups defined by energy$stature
class(x)
x

In [ ]:
split(1:10, c("A", "B"))
#1 2 3 4 5 6 7 8 9 10
#A B A B A B A B A B 

# list
# A: 1,3,5,7,9
# B: 2,4,6,8,10

In [ ]:
x$lean
x[[1]]

In [ ]:
energy[[1]]

In [ ]:
x=list(a=1:4, b=5:9, c=c('hello', 'world'), mymatrix=matrix(1:6, 2,3))
x
# x$m[2,2]
names(x)
x[['mymatrix']][,2]
# x$a
# x[[1]]
# x[[2]]
# x[['c']]

In [ ]:
ls()
rm(a)
ls()

In [ ]:
getwd()

In [ ]:
file.show("table.txt")

In [ ]:
file.show("table.csv")

In [ ]:
read.table

In [ ]:
mytable=read.table(file="table.txt", header=TRUE, sep=" ");mytable
class(mytable)
sapply(mytable, class) #get data type for each column

In [ ]:
mytable
write.table(mytable, file="mytable.txt")

In [ ]:
?write.table

In [ ]:
file.show("mytable.txt")

In [ ]:
# write.csv(mytable, file="mytable.csv")
write.csv(mytable, file="mytable.csv", row.names=FALSE) #do not include row numbers

In [ ]:
file.show("mytable.csv")

In [ ]:
mytable=read.csv(file="mytable.csv", header=TRUE);mytable
names(mytable)

In [ ]:
mytable=read.csv(file="table.csv", header=TRUE);mytable
names(mytable)

In [ ]:
mytable=read.csv(file="table.txt", header=TRUE);mytable
names(mytable)

In [ ]:
lines=readLines("table.csv")
lines
lines=readLines("table.txt")
lines
lines[1]
lines[2]
lines[3]

In [ ]:
?writeLines

In [ ]:
fileConn<-file("output.txt")
writeLines(c("Hello","World"), fileConn)
close(fileConn)

In [ ]:
x=data.frame(a=1, b=2); x
dput(x)

In [ ]:
str(x)

In [ ]:
summary(x)

In [ ]:
dput(x, file="x.R")

In [ ]:
file.show("x.R")

In [ ]:
dget("x.R")
structure(list(a = 1, b = 2), class = "data.frame", row.names = c(NA, 
-1L))
data.frame(a=1, b=2)

In [ ]:
y=dget("x.R") # you can think dget inserts the content here.
y

In [ ]:
y=structure(list(a = 1, b = 2), class = "data.frame", row.names = c(NA, 
-1L))
y

In [ ]:
print("====================")
x=8
y=9
# dump(c('x', 'y'))  # by default it dumps to file "dumpdata.R"
dump(c('x', 'y'), file='xy.R')

In [ ]:
file.show("xy.R")

In [ ]:
ls()
rm(x, y)
ls()

In [ ]:
source("xy.R") # source both inserts and executes the content here
x

In [ ]:
x <- serialize(list(1,2,3), NULL)
print(x)
y=unserialize(x)
y

In [ ]:
a=data.frame(x = rnorm(100), y = runif(100)); head(a)
b=c(3, 4.4, 1 / 3); b

In [ ]:
save(a, b, file = "mydata.rda")

In [ ]:
rm(a, b)
ls()

In [ ]:
load("mydata.rda")

In [ ]:
ls()
head(a)
b

In [ ]:
save.image(file="alldata.RData") #then this file can be opened in another R session or even on different computer.

In [ ]:
mult <- function(x, y) {
    x*y
}

In [ ]:
mult(9, 9)

In [ ]:
dput(mult, file="mymult.R")

In [ ]:
file.show("mymult.R")

In [ ]:
dump(c('mult'), file="myfun.R")

In [ ]:
file.show("myfun.R")

In [ ]:
# calling the functions
# this is the file where we will call the functions in myfun.R and mymult.R
times <- dget("mymult.R")
times(-4:4, 2)

source("myfun.R")
mult(-4:4, 2)

In [ ]:
x=5

if (x>9) 
{
    print(2)
} else
{
    print(4)
}

In [ ]:
x=8

if(x<5){
    print(1)
} else if (x<10)  #the conditions are better to be exclusive from each other
# } else if (5<=x & x<10) 
        {
        print(2)
        }else{ # x>=10
           print(3)
        }

In [ ]:
x=runif(1, 0, 10);x
if (x>3) print(10) else print(0)


In [ ]:
?runif

In [ ]:
x=runif(1, 0, 10)
if (x>3) 10 else 0

In [ ]:
x=runif(1, 0, 10)
y=if (x>3) 10 else 0
print(y)
# x=runif(1, 0, 10)
print(ifelse(x>3, 10, 0))

In [ ]:
ifelse #it creates both vectors, the yes and the no, and then subsets.

In [ ]:
rep(c(1,2,3), length.out =5)
# ?rep

In [ ]:
x=6:-4
sqrt(x)

In [ ]:
y=ifelse(x>=0, x, 0);y
sqrt(y)

In [ ]:
ifelse(x>=0, sqrt(x), 0)

In [ ]:
ifelse(x>=0, {print(x);sqrt(x)}, {print("negative");0}) #recycling happens within ifelse function as seen above

In [ ]:
x=c(1,2,3)
typeof(x)  #R internal type or storage mode
class(x)   #object's class attribute, if not, it use the result of typeof
# ?typeof
# ?class
y=data.frame(x=1:2, y=3:4)
typeof(y)
class(y)

In [ ]:
yes <- 1:3
no <- pi^(0:3)
typeof(ifelse(NA,    yes, no)) # logical
typeof(ifelse(TRUE,  yes, no)) # integer
typeof(ifelse(FALSE, yes, no)) # double

In [ ]:
for(i in 1:10) print(i)

In [ ]:
x=c('a', 'b', 'c')
for (i in x) print(i)
for (i in 1:length(x)) print(x[i])

In [ ]:
x=c('a', 'b', 'c')
# x=c()
1:length(x)
for (i in 1:length(x)) print(i)
"=================="
seq_along(x) #generate the index vector safely
for (i in seq_along(x)) print(i)

In [ ]:
?seq_along

In [6]:
for (i in seq_along(x)) print(i);print(i*2)
"===================="
for (i in seq_along(x)) {print(i);print(i*2)}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 12


[1] "===================="

[1] 1
[1] 2
[1] 2
[1] 4
[1] 3
[1] 6
[1] 4
[1] 8
[1] 5
[1] 10
[1] 6
[1] 12


In [ ]:
x=matrix(1:6, 2, 3)
print(x)

nrow(x)
ncol(x)
seq_len(nrow(x))
seq_len(ncol(x))
seq_len(10)
seq_len(0)
seq_along(10)
seq_along(1:10)

for(i in seq_len(nrow(x))) {
    for (j in seq_len(ncol(x))) {
        print(paste("i=", i, "j=", j, "x=", x[i, j], sep=" "))
#         print(x[i,j])
        }
}

In [ ]:
x <- 1
repeat {
    print(x)
    x = x+1
    if (x == 6) break
}

In [ ]:
x=data.frame(1:3, 10001:10003, c("a", "b", "c","a", "b", "c","a", "b", "c","a", "b", "c","a", "b", "c"))
x$c..a....b....c....a....b....c....a....b....c....a....b..
# y=list(a=1:3, b=4:6, c=4:6)
# # x$a
# # y$a
# x[2]
# x$2

In [ ]:
mydf=data.frame(a=1:3, "b a "=4:6)
mydf

In [ ]:
mydf$b.

In [ ]:
typeof(1:4)

In [ ]:
matrix(1:5, 2, 3)

# 1 3 1
# 2 4 2

In [ ]:
matrix(1:5, nrow=3)
# 1 3 5
# 2 4 1